python-interpreter-path = "backend/venv/Scripts/python.exe"
site-package-path = [
    "backend/venv/Lib/site-packages"
]
search-path = [
    ".",
    "backend"
]
extra-search-paths = [
    "backend/venv/Lib/site-packages"
]
project-excludes = [
    "**/.[!/.]*",
    "**/*venv/**",
    "**/__pycache__/**",
    "**/_pyrefly_virtual_/**",
    "**/.pytest_cache/**",
    "**/frontend/**"
]
